<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 23/05/2019
 * Time: 09:35
 */


require_once 'BaseController.php';
require_once __DIR__.'/../models/ClientModel.php';

class ClientsController extends BaseController
{
    function __construct(){
        parent::__construct();
        $this->model = new ClientModel();
    }

    function getZones(){
        $this->returnSuccess(200,$this->getModel()->getSpinner("loccli"));

    }

    function get(){

        if(isset($_GET['method'])){
            $this->method();
        }else if($this->validateId()){
            $entity = $this->getModel()->findById($_GET['id']);
            if(!empty($entity)){
                $this->returnSuccess(200,$entity);
            }else{
                $this->returnError(404,"ENTITY NOT FOUND");
            }
        }else{
           // $this->returnSuccess(200,$this->getModel()->findAllByNameCli($this->getFilters(),$this->getPaginator()));
            $this->returnSuccess(200,$this->assignFilter());
        }
    }

    public function getFilters()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
           // $filters[] = 'nomcli like "%'.$_GET['query'].'%"';
            $filters[] = 'nomcli like "'.$_GET['query'].'%" OR nomcli like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }

    public function getFiltersContain()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
             $filters[] = 'nomcli like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }

    public function getFiltersFirstLetter()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'nomcli like "'.$_GET['query'].'%"';
        }
        return $filters;
    }

    public function getFiltersContainCom()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'comcli like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }

    public function getFiltersFirstLetterCom()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'comcli like "'.$_GET['query'].'%"';
        }
        return $filters;
    }

    public function assignFilter(){
        $res=$this->getModel()->findAllByNameCli($this->getFiltersFirstLetter(),$this->getPaginator());
        $resContainCom=$this->getModel()->findAllByNameCli($this->getFiltersContainCom(),$this->getPaginator());
        $resContain=$this->getModel()->findAllByNameCli($this->getFiltersContain(),$this->getPaginator());
        $resCom=$this->getModel()->findAllByNameCli($this->getFiltersFirstLetterCom(),$this->getPaginator());

        return $res+$resCom+$resContainCom+$resContain;
    }


}